import * as geo_arg from 'world-countries/data/arg.geo.json'
import * as geo_aus from 'world-countries/data/aus.geo.json'
import * as geo_aut from 'world-countries/data/aut.geo.json'
import * as geo_bel from 'world-countries/data/bel.geo.json'
import * as geo_che from 'world-countries/data/che.geo.json'
import * as geo_chl from 'world-countries/data/chl.geo.json'
import * as geo_cze from 'world-countries/data/cze.geo.json'
import * as geo_deu from 'world-countries/data/deu.geo.json'
import * as geo_esp from 'world-countries/data/esp.geo.json'
import * as geo_fra from 'world-countries/data/fra.geo.json'
import * as geo_gbr from 'world-countries/data/gbr.geo.json'
import * as geo_geo from 'world-countries/data/geo.geo.json'
import * as geo_grc from 'world-countries/data/grc.geo.json'
import * as geo_hun from 'world-countries/data/hun.geo.json'
import * as geo_isr from 'world-countries/data/isr.geo.json'
import * as geo_ita from 'world-countries/data/ita.geo.json'
import * as geo_mda from 'world-countries/data/mda.geo.json'
import * as geo_nzl from 'world-countries/data/nzl.geo.json'
import * as geo_prt from 'world-countries/data/prt.geo.json'
import * as geo_svk from 'world-countries/data/svk.geo.json'
import * as geo_ukr from 'world-countries/data/ukr.geo.json'
import * as geo_usa from 'world-countries/data/usa.geo.json'
import * as geo_zaf from 'world-countries/data/zaf.geo.json'
import * as geo_jpn from 'world-countries/data/jpn.geo.json'
import * as geo_lbn from 'world-countries/data/lbn.geo.json'
import * as geo_hrv from 'world-countries/data/hrv.geo.json'

export const countriesGeoJsonMap: Record<string, GeoJSON.FeatureCollection> = {
  Italy: geo_ita as unknown as GeoJSON.FeatureCollection,
  France: geo_fra as unknown as GeoJSON.FeatureCollection,
  Spain: geo_esp as unknown as GeoJSON.FeatureCollection,
  'South Africa': geo_zaf as unknown as GeoJSON.FeatureCollection,
  Moldova: geo_mda as unknown as GeoJSON.FeatureCollection,
  Australia: geo_aus as unknown as GeoJSON.FeatureCollection,
  'New Zealand': geo_nzl as unknown as GeoJSON.FeatureCollection,
  USA: geo_usa as unknown as GeoJSON.FeatureCollection,
  Hungary: geo_hun as unknown as GeoJSON.FeatureCollection,
  England: geo_gbr as unknown as GeoJSON.FeatureCollection,
  Germany: geo_deu as unknown as GeoJSON.FeatureCollection,
  Argentina: geo_arg as unknown as GeoJSON.FeatureCollection,
  Greece: geo_grc as unknown as GeoJSON.FeatureCollection,
  Chile: geo_chl as unknown as GeoJSON.FeatureCollection,
  Georgia: geo_geo as unknown as GeoJSON.FeatureCollection,
  Ukraine: geo_ukr as unknown as GeoJSON.FeatureCollection,
  Belgium: geo_bel as unknown as GeoJSON.FeatureCollection,
  Portugal: geo_prt as unknown as GeoJSON.FeatureCollection,
  Slovakia: geo_svk as unknown as GeoJSON.FeatureCollection,
  Austria: geo_aut as unknown as GeoJSON.FeatureCollection,
  Israel: geo_isr as unknown as GeoJSON.FeatureCollection,
  'Czech Republic': geo_cze as unknown as GeoJSON.FeatureCollection,
  Switzerland: geo_che as unknown as GeoJSON.FeatureCollection,
  Japan: geo_jpn as unknown as GeoJSON.FeatureCollection,
  Lebanon: geo_lbn as unknown as GeoJSON.FeatureCollection,
  Croatia: geo_hrv as unknown as GeoJSON.FeatureCollection,
}

export function countriesGeoJson(names: string[]): GeoJSON.FeatureCollection[] {
  return names.map((name) => countriesGeoJsonMap[name])
}

/*
import * as geo_abw from 'world-countries/data/abw.geo.json'
import * as geo_afg from 'world-countries/data/afg.geo.json'
import * as geo_ago from 'world-countries/data/ago.geo.json'
import * as geo_aia from 'world-countries/data/aia.geo.json'
import * as geo_ala from 'world-countries/data/ala.geo.json'
import * as geo_alb from 'world-countries/data/alb.geo.json'
import * as geo_and from 'world-countries/data/and.geo.json'
import * as geo_are from 'world-countries/data/are.geo.json'
import * as geo_arg from 'world-countries/data/arg.geo.json'
import * as geo_arm from 'world-countries/data/arm.geo.json'
import * as geo_asm from 'world-countries/data/asm.geo.json'
import * as geo_ata from 'world-countries/data/ata.geo.json'
import * as geo_atf from 'world-countries/data/atf.geo.json'
import * as geo_atg from 'world-countries/data/atg.geo.json'
import * as geo_aus from 'world-countries/data/aus.geo.json'
import * as geo_aut from 'world-countries/data/aut.geo.json'
import * as geo_aze from 'world-countries/data/aze.geo.json'
import * as geo_bdi from 'world-countries/data/bdi.geo.json'
import * as geo_bel from 'world-countries/data/bel.geo.json'
import * as geo_ben from 'world-countries/data/ben.geo.json'
import * as geo_bes from 'world-countries/data/bes.geo.json'
import * as geo_bfa from 'world-countries/data/bfa.geo.json'
import * as geo_bgd from 'world-countries/data/bgd.geo.json'
import * as geo_bgr from 'world-countries/data/bgr.geo.json'
import * as geo_bhr from 'world-countries/data/bhr.geo.json'
import * as geo_bhs from 'world-countries/data/bhs.geo.json'
import * as geo_bih from 'world-countries/data/bih.geo.json'
import * as geo_blm from 'world-countries/data/blm.geo.json'
import * as geo_blr from 'world-countries/data/blr.geo.json'
import * as geo_blz from 'world-countries/data/blz.geo.json'
import * as geo_bmu from 'world-countries/data/bmu.geo.json'
import * as geo_bol from 'world-countries/data/bol.geo.json'
import * as geo_bra from 'world-countries/data/bra.geo.json'
import * as geo_brb from 'world-countries/data/brb.geo.json'
import * as geo_brn from 'world-countries/data/brn.geo.json'
import * as geo_btn from 'world-countries/data/btn.geo.json'
import * as geo_bvt from 'world-countries/data/bvt.geo.json'
import * as geo_bwa from 'world-countries/data/bwa.geo.json'
import * as geo_caf from 'world-countries/data/caf.geo.json'
import * as geo_can from 'world-countries/data/can.geo.json'
import * as geo_cck from 'world-countries/data/cck.geo.json'
import * as geo_chl from 'world-countries/data/chl.geo.json'
import * as geo_chn from 'world-countries/data/chn.geo.json'
import * as geo_civ from 'world-countries/data/civ.geo.json'
import * as geo_cmr from 'world-countries/data/cmr.geo.json'
import * as geo_cod from 'world-countries/data/cod.geo.json'
import * as geo_cog from 'world-countries/data/cog.geo.json'
import * as geo_cok from 'world-countries/data/cok.geo.json'
import * as geo_col from 'world-countries/data/col.geo.json'
import * as geo_com from 'world-countries/data/com.geo.json'
import * as geo_cpv from 'world-countries/data/cpv.geo.json'
import * as geo_cri from 'world-countries/data/cri.geo.json'
import * as geo_cub from 'world-countries/data/cub.geo.json'
import * as geo_cuw from 'world-countries/data/cuw.geo.json'
import * as geo_cxr from 'world-countries/data/cxr.geo.json'
import * as geo_cym from 'world-countries/data/cym.geo.json'
import * as geo_cyp from 'world-countries/data/cyp.geo.json'
import * as geo_cze from 'world-countries/data/cze.geo.json'
import * as geo_deu from 'world-countries/data/deu.geo.json'
import * as geo_dji from 'world-countries/data/dji.geo.json'
import * as geo_dma from 'world-countries/data/dma.geo.json'
import * as geo_dnk from 'world-countries/data/dnk.geo.json'
import * as geo_dom from 'world-countries/data/dom.geo.json'
import * as geo_dza from 'world-countries/data/dza.geo.json'
import * as geo_ecu from 'world-countries/data/ecu.geo.json'
import * as geo_egy from 'world-countries/data/egy.geo.json'
import * as geo_eri from 'world-countries/data/eri.geo.json'
import * as geo_esh from 'world-countries/data/esh.geo.json'
import * as geo_esp from 'world-countries/data/esp.geo.json'
import * as geo_est from 'world-countries/data/est.geo.json'
import * as geo_eth from 'world-countries/data/eth.geo.json'
import * as geo_fin from 'world-countries/data/fin.geo.json'
import * as geo_fji from 'world-countries/data/fji.geo.json'
import * as geo_flk from 'world-countries/data/flk.geo.json'
import * as geo_fra from 'world-countries/data/fra.geo.json'
import * as geo_fro from 'world-countries/data/fro.geo.json'
import * as geo_fsm from 'world-countries/data/fsm.geo.json'
import * as geo_gab from 'world-countries/data/gab.geo.json'
import * as geo_gbr from 'world-countries/data/gbr.geo.json'
import * as geo_geo from 'world-countries/data/geo.geo.json'
import * as geo_ggy from 'world-countries/data/ggy.geo.json'
import * as geo_gha from 'world-countries/data/gha.geo.json'
import * as geo_gib from 'world-countries/data/gib.geo.json'
import * as geo_gin from 'world-countries/data/gin.geo.json'
import * as geo_glp from 'world-countries/data/glp.geo.json'
import * as geo_gmb from 'world-countries/data/gmb.geo.json'
import * as geo_gnb from 'world-countries/data/gnb.geo.json'
import * as geo_gnq from 'world-countries/data/gnq.geo.json'
import * as geo_grc from 'world-countries/data/grc.geo.json'
import * as geo_grd from 'world-countries/data/grd.geo.json'
import * as geo_grl from 'world-countries/data/grl.geo.json'
import * as geo_gtm from 'world-countries/data/gtm.geo.json'
import * as geo_guf from 'world-countries/data/guf.geo.json'
import * as geo_gum from 'world-countries/data/gum.geo.json'
import * as geo_guy from 'world-countries/data/guy.geo.json'
import * as geo_hkg from 'world-countries/data/hkg.geo.json'
import * as geo_hmd from 'world-countries/data/hmd.geo.json'
import * as geo_hnd from 'world-countries/data/hnd.geo.json'
import * as geo_hrv from 'world-countries/data/hrv.geo.json'
import * as geo_hti from 'world-countries/data/hti.geo.json'
import * as geo_hun from 'world-countries/data/hun.geo.json'
import * as geo_idn from 'world-countries/data/idn.geo.json'
import * as geo_imn from 'world-countries/data/imn.geo.json'
import * as geo_ind from 'world-countries/data/ind.geo.json'
import * as geo_iot from 'world-countries/data/iot.geo.json'
import * as geo_irl from 'world-countries/data/irl.geo.json'
import * as geo_irn from 'world-countries/data/irn.geo.json'
import * as geo_irq from 'world-countries/data/irq.geo.json'
import * as geo_isl from 'world-countries/data/isl.geo.json'
import * as geo_isr from 'world-countries/data/isr.geo.json'
import * as geo_ita from 'world-countries/data/ita.geo.json'
import * as geo_jam from 'world-countries/data/jam.geo.json'
import * as geo_jey from 'world-countries/data/jey.geo.json'
import * as geo_jor from 'world-countries/data/jor.geo.json'
import * as geo_jpn from 'world-countries/data/jpn.geo.json'
import * as geo_kaz from 'world-countries/data/kaz.geo.json'
import * as geo_ken from 'world-countries/data/ken.geo.json'
import * as geo_kgz from 'world-countries/data/kgz.geo.json'
import * as geo_khm from 'world-countries/data/khm.geo.json'
import * as geo_kir from 'world-countries/data/kir.geo.json'
import * as geo_kna from 'world-countries/data/kna.geo.json'
import * as geo_kor from 'world-countries/data/kor.geo.json'
import * as geo_kwt from 'world-countries/data/kwt.geo.json'
import * as geo_lao from 'world-countries/data/lao.geo.json'
import * as geo_lbn from 'world-countries/data/lbn.geo.json'
import * as geo_lbr from 'world-countries/data/lbr.geo.json'
import * as geo_lby from 'world-countries/data/lby.geo.json'
import * as geo_lca from 'world-countries/data/lca.geo.json'
import * as geo_lie from 'world-countries/data/lie.geo.json'
import * as geo_lka from 'world-countries/data/lka.geo.json'
import * as geo_lso from 'world-countries/data/lso.geo.json'
import * as geo_ltu from 'world-countries/data/ltu.geo.json'
import * as geo_lux from 'world-countries/data/lux.geo.json'
import * as geo_lva from 'world-countries/data/lva.geo.json'
import * as geo_mac from 'world-countries/data/mac.geo.json'
import * as geo_maf from 'world-countries/data/maf.geo.json'
import * as geo_mar from 'world-countries/data/mar.geo.json'
import * as geo_mco from 'world-countries/data/mco.geo.json'
import * as geo_mda from 'world-countries/data/mda.geo.json'
import * as geo_mdg from 'world-countries/data/mdg.geo.json'
import * as geo_mdv from 'world-countries/data/mdv.geo.json'
import * as geo_mex from 'world-countries/data/mex.geo.json'
import * as geo_mhl from 'world-countries/data/mhl.geo.json'
import * as geo_mkd from 'world-countries/data/mkd.geo.json'
import * as geo_mli from 'world-countries/data/mli.geo.json'
import * as geo_mlt from 'world-countries/data/mlt.geo.json'
import * as geo_mmr from 'world-countries/data/mmr.geo.json'
import * as geo_mne from 'world-countries/data/mne.geo.json'
import * as geo_mng from 'world-countries/data/mng.geo.json'
import * as geo_mnp from 'world-countries/data/mnp.geo.json'
import * as geo_moz from 'world-countries/data/moz.geo.json'
import * as geo_mrt from 'world-countries/data/mrt.geo.json'
import * as geo_msr from 'world-countries/data/msr.geo.json'
import * as geo_mtq from 'world-countries/data/mtq.geo.json'
import * as geo_mus from 'world-countries/data/mus.geo.json'
import * as geo_mwi from 'world-countries/data/mwi.geo.json'
import * as geo_mys from 'world-countries/data/mys.geo.json'
import * as geo_myt from 'world-countries/data/myt.geo.json'
import * as geo_nam from 'world-countries/data/nam.geo.json'
import * as geo_ncl from 'world-countries/data/ncl.geo.json'
import * as geo_ner from 'world-countries/data/ner.geo.json'
import * as geo_nfk from 'world-countries/data/nfk.geo.json'
import * as geo_nga from 'world-countries/data/nga.geo.json'
import * as geo_nic from 'world-countries/data/nic.geo.json'
import * as geo_niu from 'world-countries/data/niu.geo.json'
import * as geo_nld from 'world-countries/data/nld.geo.json'
import * as geo_nor from 'world-countries/data/nor.geo.json'
import * as geo_npl from 'world-countries/data/npl.geo.json'
import * as geo_nru from 'world-countries/data/nru.geo.json'
import * as geo_nzl from 'world-countries/data/nzl.geo.json'
import * as geo_omn from 'world-countries/data/omn.geo.json'
import * as geo_pak from 'world-countries/data/pak.geo.json'
import * as geo_pan from 'world-countries/data/pan.geo.json'
import * as geo_pcn from 'world-countries/data/pcn.geo.json'
import * as geo_per from 'world-countries/data/per.geo.json'
import * as geo_phl from 'world-countries/data/phl.geo.json'
import * as geo_plw from 'world-countries/data/plw.geo.json'
import * as geo_png from 'world-countries/data/png.geo.json'
import * as geo_pol from 'world-countries/data/pol.geo.json'
import * as geo_pri from 'world-countries/data/pri.geo.json'
import * as geo_prk from 'world-countries/data/prk.geo.json'
import * as geo_prt from 'world-countries/data/prt.geo.json'
import * as geo_pry from 'world-countries/data/pry.geo.json'
import * as geo_pse from 'world-countries/data/pse.geo.json'
import * as geo_pyf from 'world-countries/data/pyf.geo.json'
import * as geo_qat from 'world-countries/data/qat.geo.json'
import * as geo_reu from 'world-countries/data/reu.geo.json'
import * as geo_rou from 'world-countries/data/rou.geo.json'
import * as geo_rus from 'world-countries/data/rus.geo.json'
import * as geo_rwa from 'world-countries/data/rwa.geo.json'
import * as geo_sau from 'world-countries/data/sau.geo.json'
import * as geo_sdn from 'world-countries/data/sdn.geo.json'
import * as geo_sen from 'world-countries/data/sen.geo.json'
import * as geo_sgp from 'world-countries/data/sgp.geo.json'
import * as geo_sgs from 'world-countries/data/sgs.geo.json'
import * as geo_shn from 'world-countries/data/shn.geo.json'
import * as geo_sjm from 'world-countries/data/sjm.geo.json'
import * as geo_slb from 'world-countries/data/slb.geo.json'
import * as geo_sle from 'world-countries/data/sle.geo.json'
import * as geo_slv from 'world-countries/data/slv.geo.json'
import * as geo_smr from 'world-countries/data/smr.geo.json'
import * as geo_som from 'world-countries/data/som.geo.json'
import * as geo_spm from 'world-countries/data/spm.geo.json'
import * as geo_srb from 'world-countries/data/srb.geo.json'
import * as geo_ssd from 'world-countries/data/ssd.geo.json'
import * as geo_stp from 'world-countries/data/stp.geo.json'
import * as geo_sur from 'world-countries/data/sur.geo.json'
import * as geo_svk from 'world-countries/data/svk.geo.json'
import * as geo_svn from 'world-countries/data/svn.geo.json'
import * as geo_swe from 'world-countries/data/swe.geo.json'
import * as geo_swz from 'world-countries/data/swz.geo.json'
import * as geo_sxm from 'world-countries/data/sxm.geo.json'
import * as geo_syc from 'world-countries/data/syc.geo.json'
import * as geo_syr from 'world-countries/data/syr.geo.json'
import * as geo_tca from 'world-countries/data/tca.geo.json'
import * as geo_tcd from 'world-countries/data/tcd.geo.json'
import * as geo_tgo from 'world-countries/data/tgo.geo.json'
import * as geo_tha from 'world-countries/data/tha.geo.json'
import * as geo_tjk from 'world-countries/data/tjk.geo.json'
import * as geo_tkl from 'world-countries/data/tkl.geo.json'
import * as geo_tkm from 'world-countries/data/tkm.geo.json'
import * as geo_tls from 'world-countries/data/tls.geo.json'
import * as geo_ton from 'world-countries/data/ton.geo.json'
import * as geo_tto from 'world-countries/data/tto.geo.json'
import * as geo_tun from 'world-countries/data/tun.geo.json'
import * as geo_tur from 'world-countries/data/tur.geo.json'
import * as geo_tuv from 'world-countries/data/tuv.geo.json'
import * as geo_twn from 'world-countries/data/twn.geo.json'
import * as geo_tza from 'world-countries/data/tza.geo.json'
import * as geo_uga from 'world-countries/data/uga.geo.json'
import * as geo_ukr from 'world-countries/data/ukr.geo.json'
import * as geo_umi from 'world-countries/data/umi.geo.json'
import * as geo_unk from 'world-countries/data/unk.geo.json'
import * as geo_ury from 'world-countries/data/ury.geo.json'
import * as geo_usa from 'world-countries/data/usa.geo.json'
import * as geo_uzb from 'world-countries/data/uzb.geo.json'
import * as geo_vat from 'world-countries/data/vat.geo.json'
import * as geo_vct from 'world-countries/data/vct.geo.json'
import * as geo_ven from 'world-countries/data/ven.geo.json'
import * as geo_vgb from 'world-countries/data/vgb.geo.json'
import * as geo_vir from 'world-countries/data/vir.geo.json'
import * as geo_vnm from 'world-countries/data/vnm.geo.json'
import * as geo_vut from 'world-countries/data/vut.geo.json'
import * as geo_wlf from 'world-countries/data/wlf.geo.json'
import * as geo_wsm from 'world-countries/data/wsm.geo.json'
import * as geo_yem from 'world-countries/data/yem.geo.json'
import * as geo_zaf from 'world-countries/data/zaf.geo.json'
import * as geo_zmb from 'world-countries/data/zmb.geo.json'
import * as geo_zwe from 'world-countries/data/zwe.geo.json'
*/

// export function allCountriesGeoJson(): GeoJSON.FeatureCollection[] {
//   return [
//     geo_abw as unknown as GeoJSON.FeatureCollection,
//     geo_afg as unknown as GeoJSON.FeatureCollection,
//     geo_ago as unknown as GeoJSON.FeatureCollection,
//     geo_aia as unknown as GeoJSON.FeatureCollection,
//     geo_ala as unknown as GeoJSON.FeatureCollection,
//     geo_alb as unknown as GeoJSON.FeatureCollection,
//     geo_and as unknown as GeoJSON.FeatureCollection,
//     geo_are as unknown as GeoJSON.FeatureCollection,
//     geo_arg as unknown as GeoJSON.FeatureCollection,
//     geo_arm as unknown as GeoJSON.FeatureCollection,
//     geo_asm as unknown as GeoJSON.FeatureCollection,
//     geo_ata as unknown as GeoJSON.FeatureCollection,
//     geo_atf as unknown as GeoJSON.FeatureCollection,
//     geo_atg as unknown as GeoJSON.FeatureCollection,
//     geo_aus as unknown as GeoJSON.FeatureCollection,
//     geo_aut as unknown as GeoJSON.FeatureCollection,
//     geo_aze as unknown as GeoJSON.FeatureCollection,
//     geo_bdi as unknown as GeoJSON.FeatureCollection,
//     geo_bel as unknown as GeoJSON.FeatureCollection,
//     geo_ben as unknown as GeoJSON.FeatureCollection,
//     geo_bes as unknown as GeoJSON.FeatureCollection,
//     geo_bfa as unknown as GeoJSON.FeatureCollection,
//     geo_bgd as unknown as GeoJSON.FeatureCollection,
//     geo_bgr as unknown as GeoJSON.FeatureCollection,
//     geo_bhr as unknown as GeoJSON.FeatureCollection,
//     geo_bhs as unknown as GeoJSON.FeatureCollection,
//     geo_bih as unknown as GeoJSON.FeatureCollection,
//     geo_blm as unknown as GeoJSON.FeatureCollection,
//     geo_blr as unknown as GeoJSON.FeatureCollection,
//     geo_blz as unknown as GeoJSON.FeatureCollection,
//     geo_bmu as unknown as GeoJSON.FeatureCollection,
//     geo_bol as unknown as GeoJSON.FeatureCollection,
//     geo_bra as unknown as GeoJSON.FeatureCollection,
//     geo_brb as unknown as GeoJSON.FeatureCollection,
//     geo_brn as unknown as GeoJSON.FeatureCollection,
//     geo_btn as unknown as GeoJSON.FeatureCollection,
//     geo_bvt as unknown as GeoJSON.FeatureCollection,
//     geo_bwa as unknown as GeoJSON.FeatureCollection,
//     geo_caf as unknown as GeoJSON.FeatureCollection,
//     geo_can as unknown as GeoJSON.FeatureCollection,
//     geo_cck as unknown as GeoJSON.FeatureCollection,
//     geo_che as unknown as GeoJSON.FeatureCollection,
//     geo_chl as unknown as GeoJSON.FeatureCollection,
//     geo_chn as unknown as GeoJSON.FeatureCollection,
//     geo_civ as unknown as GeoJSON.FeatureCollection,
//     geo_cmr as unknown as GeoJSON.FeatureCollection,
//     geo_cod as unknown as GeoJSON.FeatureCollection,
//     geo_cog as unknown as GeoJSON.FeatureCollection,
//     geo_cok as unknown as GeoJSON.FeatureCollection,
//     geo_col as unknown as GeoJSON.FeatureCollection,
//     geo_com as unknown as GeoJSON.FeatureCollection,
//     geo_cpv as unknown as GeoJSON.FeatureCollection,
//     geo_cri as unknown as GeoJSON.FeatureCollection,
//     geo_cub as unknown as GeoJSON.FeatureCollection,
//     geo_cuw as unknown as GeoJSON.FeatureCollection,
//     geo_cxr as unknown as GeoJSON.FeatureCollection,
//     geo_cym as unknown as GeoJSON.FeatureCollection,
//     geo_cyp as unknown as GeoJSON.FeatureCollection,
//     geo_cze as unknown as GeoJSON.FeatureCollection,
//     geo_deu as unknown as GeoJSON.FeatureCollection,
//     geo_dji as unknown as GeoJSON.FeatureCollection,
//     geo_dma as unknown as GeoJSON.FeatureCollection,
//     geo_dnk as unknown as GeoJSON.FeatureCollection,
//     geo_dom as unknown as GeoJSON.FeatureCollection,
//     geo_dza as unknown as GeoJSON.FeatureCollection,
//     geo_ecu as unknown as GeoJSON.FeatureCollection,
//     geo_egy as unknown as GeoJSON.FeatureCollection,
//     geo_eri as unknown as GeoJSON.FeatureCollection,
//     geo_esh as unknown as GeoJSON.FeatureCollection,
//     geo_esp as unknown as GeoJSON.FeatureCollection,
//     geo_est as unknown as GeoJSON.FeatureCollection,
//     geo_eth as unknown as GeoJSON.FeatureCollection,
//     geo_fin as unknown as GeoJSON.FeatureCollection,
//     geo_fji as unknown as GeoJSON.FeatureCollection,
//     geo_flk as unknown as GeoJSON.FeatureCollection,
//     geo_fra as unknown as GeoJSON.FeatureCollection,
//     geo_fro as unknown as GeoJSON.FeatureCollection,
//     geo_fsm as unknown as GeoJSON.FeatureCollection,
//     geo_gab as unknown as GeoJSON.FeatureCollection,
//     geo_gbr as unknown as GeoJSON.FeatureCollection,
//     geo_geo as unknown as GeoJSON.FeatureCollection,
//     geo_ggy as unknown as GeoJSON.FeatureCollection,
//     geo_gha as unknown as GeoJSON.FeatureCollection,
//     geo_gib as unknown as GeoJSON.FeatureCollection,
//     geo_gin as unknown as GeoJSON.FeatureCollection,
//     geo_glp as unknown as GeoJSON.FeatureCollection,
//     geo_gmb as unknown as GeoJSON.FeatureCollection,
//     geo_gnb as unknown as GeoJSON.FeatureCollection,
//     geo_gnq as unknown as GeoJSON.FeatureCollection,
//     geo_grc as unknown as GeoJSON.FeatureCollection,
//     geo_grd as unknown as GeoJSON.FeatureCollection,
//     geo_grl as unknown as GeoJSON.FeatureCollection,
//     geo_gtm as unknown as GeoJSON.FeatureCollection,
//     geo_guf as unknown as GeoJSON.FeatureCollection,
//     geo_gum as unknown as GeoJSON.FeatureCollection,
//     geo_guy as unknown as GeoJSON.FeatureCollection,
//     geo_hkg as unknown as GeoJSON.FeatureCollection,
//     geo_hmd as unknown as GeoJSON.FeatureCollection,
//     geo_hnd as unknown as GeoJSON.FeatureCollection,
//     geo_hrv as unknown as GeoJSON.FeatureCollection,
//     geo_hti as unknown as GeoJSON.FeatureCollection,
//     geo_hun as unknown as GeoJSON.FeatureCollection,
//     geo_idn as unknown as GeoJSON.FeatureCollection,
//     geo_imn as unknown as GeoJSON.FeatureCollection,
//     geo_ind as unknown as GeoJSON.FeatureCollection,
//     geo_iot as unknown as GeoJSON.FeatureCollection,
//     geo_irl as unknown as GeoJSON.FeatureCollection,
//     geo_irn as unknown as GeoJSON.FeatureCollection,
//     geo_irq as unknown as GeoJSON.FeatureCollection,
//     geo_isl as unknown as GeoJSON.FeatureCollection,
//     geo_isr as unknown as GeoJSON.FeatureCollection,
//     geo_ita as unknown as GeoJSON.FeatureCollection,
//     geo_jam as unknown as GeoJSON.FeatureCollection,
//     geo_jey as unknown as GeoJSON.FeatureCollection,
//     geo_jor as unknown as GeoJSON.FeatureCollection,
//     geo_jpn as unknown as GeoJSON.FeatureCollection,
//     geo_kaz as unknown as GeoJSON.FeatureCollection,
//     geo_ken as unknown as GeoJSON.FeatureCollection,
//     geo_kgz as unknown as GeoJSON.FeatureCollection,
//     geo_khm as unknown as GeoJSON.FeatureCollection,
//     geo_kir as unknown as GeoJSON.FeatureCollection,
//     geo_kna as unknown as GeoJSON.FeatureCollection,
//     geo_kor as unknown as GeoJSON.FeatureCollection,
//     geo_kwt as unknown as GeoJSON.FeatureCollection,
//     geo_lao as unknown as GeoJSON.FeatureCollection,
//     geo_lbn as unknown as GeoJSON.FeatureCollection,
//     geo_lbr as unknown as GeoJSON.FeatureCollection,
//     geo_lby as unknown as GeoJSON.FeatureCollection,
//     geo_lca as unknown as GeoJSON.FeatureCollection,
//     geo_lie as unknown as GeoJSON.FeatureCollection,
//     geo_lka as unknown as GeoJSON.FeatureCollection,
//     geo_lso as unknown as GeoJSON.FeatureCollection,
//     geo_ltu as unknown as GeoJSON.FeatureCollection,
//     geo_lux as unknown as GeoJSON.FeatureCollection,
//     geo_lva as unknown as GeoJSON.FeatureCollection,
//     geo_mac as unknown as GeoJSON.FeatureCollection,
//     geo_maf as unknown as GeoJSON.FeatureCollection,
//     geo_mar as unknown as GeoJSON.FeatureCollection,
//     geo_mco as unknown as GeoJSON.FeatureCollection,
//     geo_mda as unknown as GeoJSON.FeatureCollection,
//     geo_mdg as unknown as GeoJSON.FeatureCollection,
//     geo_mdv as unknown as GeoJSON.FeatureCollection,
//     geo_mex as unknown as GeoJSON.FeatureCollection,
//     geo_mhl as unknown as GeoJSON.FeatureCollection,
//     geo_mkd as unknown as GeoJSON.FeatureCollection,
//     geo_mli as unknown as GeoJSON.FeatureCollection,
//     geo_mlt as unknown as GeoJSON.FeatureCollection,
//     geo_mmr as unknown as GeoJSON.FeatureCollection,
//     geo_mne as unknown as GeoJSON.FeatureCollection,
//     geo_mng as unknown as GeoJSON.FeatureCollection,
//     geo_mnp as unknown as GeoJSON.FeatureCollection,
//     geo_moz as unknown as GeoJSON.FeatureCollection,
//     geo_mrt as unknown as GeoJSON.FeatureCollection,
//     geo_msr as unknown as GeoJSON.FeatureCollection,
//     geo_mtq as unknown as GeoJSON.FeatureCollection,
//     geo_mus as unknown as GeoJSON.FeatureCollection,
//     geo_mwi as unknown as GeoJSON.FeatureCollection,
//     geo_mys as unknown as GeoJSON.FeatureCollection,
//     geo_myt as unknown as GeoJSON.FeatureCollection,
//     geo_nam as unknown as GeoJSON.FeatureCollection,
//     geo_ncl as unknown as GeoJSON.FeatureCollection,
//     geo_ner as unknown as GeoJSON.FeatureCollection,
//     geo_nfk as unknown as GeoJSON.FeatureCollection,
//     geo_nga as unknown as GeoJSON.FeatureCollection,
//     geo_nic as unknown as GeoJSON.FeatureCollection,
//     geo_niu as unknown as GeoJSON.FeatureCollection,
//     geo_nld as unknown as GeoJSON.FeatureCollection,
//     geo_nor as unknown as GeoJSON.FeatureCollection,
//     geo_npl as unknown as GeoJSON.FeatureCollection,
//     geo_nru as unknown as GeoJSON.FeatureCollection,
//     geo_nzl as unknown as GeoJSON.FeatureCollection,
//     geo_omn as unknown as GeoJSON.FeatureCollection,
//     geo_pak as unknown as GeoJSON.FeatureCollection,
//     geo_pan as unknown as GeoJSON.FeatureCollection,
//     geo_pcn as unknown as GeoJSON.FeatureCollection,
//     geo_per as unknown as GeoJSON.FeatureCollection,
//     geo_phl as unknown as GeoJSON.FeatureCollection,
//     geo_plw as unknown as GeoJSON.FeatureCollection,
//     geo_png as unknown as GeoJSON.FeatureCollection,
//     geo_pol as unknown as GeoJSON.FeatureCollection,
//     geo_pri as unknown as GeoJSON.FeatureCollection,
//     geo_prk as unknown as GeoJSON.FeatureCollection,
//     geo_prt as unknown as GeoJSON.FeatureCollection,
//     geo_pry as unknown as GeoJSON.FeatureCollection,
//     geo_pse as unknown as GeoJSON.FeatureCollection,
//     geo_pyf as unknown as GeoJSON.FeatureCollection,
//     geo_qat as unknown as GeoJSON.FeatureCollection,
//     geo_reu as unknown as GeoJSON.FeatureCollection,
//     geo_rou as unknown as GeoJSON.FeatureCollection,
//     geo_rus as unknown as GeoJSON.FeatureCollection,
//     geo_rwa as unknown as GeoJSON.FeatureCollection,
//     geo_sau as unknown as GeoJSON.FeatureCollection,
//     geo_sdn as unknown as GeoJSON.FeatureCollection,
//     geo_sen as unknown as GeoJSON.FeatureCollection,
//     geo_sgp as unknown as GeoJSON.FeatureCollection,
//     geo_sgs as unknown as GeoJSON.FeatureCollection,
//     geo_shn as unknown as GeoJSON.FeatureCollection,
//     geo_sjm as unknown as GeoJSON.FeatureCollection,
//     geo_slb as unknown as GeoJSON.FeatureCollection,
//     geo_sle as unknown as GeoJSON.FeatureCollection,
//     geo_slv as unknown as GeoJSON.FeatureCollection,
//     geo_smr as unknown as GeoJSON.FeatureCollection,
//     geo_som as unknown as GeoJSON.FeatureCollection,
//     geo_spm as unknown as GeoJSON.FeatureCollection,
//     geo_srb as unknown as GeoJSON.FeatureCollection,
//     geo_ssd as unknown as GeoJSON.FeatureCollection,
//     geo_stp as unknown as GeoJSON.FeatureCollection,
//     geo_sur as unknown as GeoJSON.FeatureCollection,
//     geo_svk as unknown as GeoJSON.FeatureCollection,
//     geo_svn as unknown as GeoJSON.FeatureCollection,
//     geo_swe as unknown as GeoJSON.FeatureCollection,
//     geo_swz as unknown as GeoJSON.FeatureCollection,
//     geo_sxm as unknown as GeoJSON.FeatureCollection,
//     geo_syc as unknown as GeoJSON.FeatureCollection,
//     geo_syr as unknown as GeoJSON.FeatureCollection,
//     geo_tca as unknown as GeoJSON.FeatureCollection,
//     geo_tcd as unknown as GeoJSON.FeatureCollection,
//     geo_tgo as unknown as GeoJSON.FeatureCollection,
//     geo_tha as unknown as GeoJSON.FeatureCollection,
//     geo_tjk as unknown as GeoJSON.FeatureCollection,
//     geo_tkl as unknown as GeoJSON.FeatureCollection,
//     geo_tkm as unknown as GeoJSON.FeatureCollection,
//     geo_tls as unknown as GeoJSON.FeatureCollection,
//     geo_ton as unknown as GeoJSON.FeatureCollection,
//     geo_tto as unknown as GeoJSON.FeatureCollection,
//     geo_tun as unknown as GeoJSON.FeatureCollection,
//     geo_tur as unknown as GeoJSON.FeatureCollection,
//     geo_tuv as unknown as GeoJSON.FeatureCollection,
//     geo_twn as unknown as GeoJSON.FeatureCollection,
//     geo_tza as unknown as GeoJSON.FeatureCollection,
//     geo_uga as unknown as GeoJSON.FeatureCollection,
//     geo_ukr as unknown as GeoJSON.FeatureCollection,
//     geo_umi as unknown as GeoJSON.FeatureCollection,
//     geo_unk as unknown as GeoJSON.FeatureCollection,
//     geo_ury as unknown as GeoJSON.FeatureCollection,
//     geo_usa as unknown as GeoJSON.FeatureCollection,
//     geo_uzb as unknown as GeoJSON.FeatureCollection,
//     geo_vat as unknown as GeoJSON.FeatureCollection,
//     geo_vct as unknown as GeoJSON.FeatureCollection,
//     geo_ven as unknown as GeoJSON.FeatureCollection,
//     geo_vgb as unknown as GeoJSON.FeatureCollection,
//     geo_vir as unknown as GeoJSON.FeatureCollection,
//     geo_vnm as unknown as GeoJSON.FeatureCollection,
//     geo_vut as unknown as GeoJSON.FeatureCollection,
//     geo_wlf as unknown as GeoJSON.FeatureCollection,
//     geo_wsm as unknown as GeoJSON.FeatureCollection,
//     geo_yem as unknown as GeoJSON.FeatureCollection,
//     geo_zaf as unknown as GeoJSON.FeatureCollection,
//     geo_zmb as unknown as GeoJSON.FeatureCollection,
//     geo_zwe as unknown as GeoJSON.FeatureCollection,
//   ]
// }
