image: haskell:latest

stages:
  - build
  - pages

.build_template: &build_template
  cache:
    paths:
      - _cache
      - .stack
  script:
    - apt-get update && apt-get install xz-utils make
    - export STACK_ROOT=`pwd`/.stack
    - make build

build:
  <<: *build_template
  stage: build
  except:
    - master

pages:
  <<: *build_template
  stage: pages
  artifacts:
    paths:
      - public
  only:
    - master
