image: fpco/stack-build:lts-12.26

before_script:
  - apt-get update && apt-get install xz-utils make
  - export STACK_ROOT=`pwd`/.stack
  - stack setup
  - stack install --only-dependencies
  - stack build

build:
  cache:
    paths:
      - _cache
      - .stack
  script:
    - stack exec -- d12frosted-io build
  except:
    - master

pages:
  cache:
    paths:
      - _cache
      - .stack
  script:
    - stack exec -- d12frosted-io build
    - cp -r assets/.well-known public/.well-known
  artifacts:
    paths:
      - public
  only:
    - master
