image: haskell:latest

stages:
  - build
  - pages

.build_template: &build_template
  cache:
    paths:
      - _cache
      - .stack
  script:
    - apt-get update
    - apt-get install -y xz-utils make
    - curl -sL https://deb.nodesource.com/setup_12.x | bash -
    - apt-get install -y nodejs
    - npm install bower -g
    - export STACK_ROOT=`pwd`/.stack
    - make build

build:
  <<: *build_template
  stage: build
  except:
    - master

pages:
  <<: *build_template
  stage: pages
  artifacts:
    paths:
      - public
  only:
    - master
