image: haskell:latest

stages:
  - build
  - pages
  - github

before_script:
  - apt-get update && apt-get install xz-utils make
  - export STACK_ROOT=`pwd`/.stack
  - stack setup
  - stack install --only-dependencies
  - stack build

build:
  stage: build
  cache:
    paths:
      - _cache
      - .stack
  script:
    - stack exec -- d12frosted-io build
  except:
    - master

pages:
  stage: pages
  cache:
    paths:
      - _cache
      - .stack
  script:
    - stack exec -- d12frosted-io build
    - cp -r assets/.well-known public/.well-known
  artifacts:
    paths:
      - public
  only:
    - master

gihub:
  stage: github
  script:
    - .ci/github_push
  only:
    - master
