#!/usr/bin/env bash

URL='https://fonts.googleapis.com/css2?family=Alegreya+Sans:ital,wght@0,100;0,300;0,400;0,500;0,700;0,800;0,900;1,100;1,300;1,400;1,500;1,700;1,800;1,900&family=M+PLUS+Rounded+1c:wght@100;300;400;500;700;800;900&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap'

curl -L -o "css/fonts.css"  "$URL"

for url in $(rg -o 'url\(([^)]+)\)' -r '$1' < css/fonts.css); do
  font=$(basename "$url")
  echo "downloading $font..."
  curl -L -o "assets/fonts/$font" "$url"
  echo "replacing link..."
  new_url="/fonts/$font"
  sed -i "s@$url@$new_url@g" css/fonts.css
done

tee -a css/fonts.css << EOF
@font-face {
  font-family: 'Material Symbols Outlined';
  font-style: normal;
  font-weight: 100 700;
  font-display: swap;
  src: url(/fonts/MaterialSymbols.woff) format('woff');
}
EOF
