name: CI

on:
  push:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
      - uses: haskell/actions/setup@v1.2.11
        with:
          ghc-version: 8.10.4

      - name: cabal cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}

      - name: Build site
        env:
          GITHUB_API_USER: ${{ secrets.API_USER_NAME }}
          GITHUB_API_SECRET: ${{ secrets.API_USER_TOKEN }}
        run: |
          cabal update
          make build

      - name: Deploy
        if: success() && github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: gh-pages
          build_dir: public
          committer: Golem <golem@d12frosted.io>
        env:
          GH_PAT: ${{ secrets.API_USER_TOKEN }}
